// Parity vectors generated by polygolem `cmd/parity_walletbatch`.
// Inputs: wallet=0xfd5041047be8c192c725a66228f141196fa3cf9c, nonce=7,
// deadline=1750000000, two Calls (USDC transfer + plain ETH send).
import 'dart:typed_data';

import 'package:polydart/src/auth/eth_hex.dart';
import 'package:polydart/src/auth/wallet_signer.dart';
import 'package:polydart/src/errors/errors.dart';
import 'package:polydart/src/wallet/deposit_wallet_signing.dart';
import 'package:test/test.dart';

const _wallet = '0xfd5041047be8c192c725a66228f141196fa3cf9c';
const _nonce = '7';
const _deadline = '1750000000';

List<WalletBatchCall> _sampleCalls() => const [
  WalletBatchCall(
    target: '0x6c030c5cc283f791b26816f325b9c632d964f8a1',
    value: '0',
    data:
        '0xa9059cbb000000000000000000000000000000000000000000000000000000000000bee0000000000000000000000000000000000000000000000000000000000000000a',
  ),
  WalletBatchCall(
    target: '0x4f9b03a3c34e9ff7c20de0f5d5b4a9b3a82a8ac4',
    value: '1000000',
    data: '0x',
  ),
];

void main() {
  group('parity vectors (cross-validated against polygolem)', () {
    test('hashStruct(Call) — call 0 (ERC-20 transfer)', () {
      expect(
        bytesToHex(hashWalletBatchCall(_sampleCalls()[0])),
        '9151fb68bd2997e4f96685aacd0aa246fbcce1dfa5e5d7ef20c6868174ce7cbb',
      );
    });

    test('hashStruct(Call) — call 1 (empty calldata)', () {
      expect(
        bytesToHex(hashWalletBatchCall(_sampleCalls()[1])),
        'f84aba7eed9f05e31b571126d197ba87edd2b3dadd1ca207d74abe1cb2834afd',
      );
    });

    test('hashStruct(Batch)', () {
      expect(
        bytesToHex(
          hashWalletBatchStruct(
            walletAddress: _wallet,
            nonce: _nonce,
            deadline: _deadline,
            calls: _sampleCalls(),
          ),
        ),
        '0115f95fd7e5bcae493a5450871fff32b5c2442e3e97affcd655dbd7a763f337',
      );
    });

    test('final EIP-712 digest', () {
      expect(
        bytesToHex(
          hashWalletBatchTypedData(
            walletAddress: _wallet,
            nonce: _nonce,
            deadline: _deadline,
            calls: _sampleCalls(),
          ),
        ),
        '317201613b73892fbf48a990ec09ab9bbf041f70f4dab174da7cb18653f6ec8f',
      );
    });
  });

  group('typed-data envelope', () {
    test('shape matches eth_signTypedData_v4 expectations', () {
      final td = buildWalletBatchTypedData(
        walletAddress: _wallet,
        nonce: _nonce,
        deadline: _deadline,
        calls: _sampleCalls(),
      );
      expect(td['primaryType'], 'Batch');
      final domain = td['domain'] as Map<String, dynamic>;
      expect(domain['name'], 'DepositWallet');
      expect(domain['version'], '1');
      expect(domain['chainId'], 137);
      expect(domain['verifyingContract'], _wallet);
      final msg = td['message'] as Map<String, dynamic>;
      final calls = msg['calls'] as List;
      expect(calls.length, 2);
      expect((calls[0] as Map)['target'], _sampleCalls()[0].target);
    });
  });

  group('validation', () {
    test('rejects empty calls', () {
      expect(
        () => hashWalletBatchStruct(
          walletAddress: _wallet,
          nonce: _nonce,
          deadline: _deadline,
          calls: const [],
        ),
        throwsA(isA<ValidationException>()),
      );
    });

    test('rejects bad target address', () {
      expect(
        () => hashWalletBatchCall(
          const WalletBatchCall(target: '0xabc', value: '0', data: '0x'),
        ),
        throwsA(isA<ValidationException>()),
      );
    });

    test('rejects non-numeric nonce', () {
      expect(
        () => hashWalletBatchStruct(
          walletAddress: _wallet,
          nonce: 'not-a-number',
          deadline: _deadline,
          calls: _sampleCalls(),
        ),
        throwsA(isA<ValidationException>()),
      );
    });
  });

  group('signWalletBatch (WalletSigner integration)', () {
    test(
      'passes the typed-data envelope to the signer and returns hex',
      () async {
        final signer = _StubSigner(
          signature: Uint8List.fromList(
            List<int>.generate(65, (i) => 0xb0 + (i % 16)),
          ),
        );
        final hex = await signWalletBatch(
          signer: signer,
          walletAddress: _wallet,
          nonce: _nonce,
          deadline: _deadline,
          calls: _sampleCalls(),
        );
        expect(hex.startsWith('0x'), isTrue);
        expect(hex.length, 132); // 65 bytes
        expect(signer.lastEnvelope, isNotNull);
        final domain = signer.lastEnvelope!['domain'] as Map<String, dynamic>;
        expect(domain['chainId'], 137);
      },
    );

    test('rejects non-Polygon signer before wallet signing', () async {
      final signer = _StubSigner(signature: Uint8List(65), chainId: 80002);

      await expectLater(
        signWalletBatch(
          signer: signer,
          walletAddress: _wallet,
          nonce: _nonce,
          deadline: _deadline,
          calls: _sampleCalls(),
        ),
        throwsA(
          isA<ValidationException>()
              .having((e) => e.field, 'field', 'chainId')
              .having(
                (e) => e.message,
                'message',
                contains('Polygon chainId=137'),
              ),
        ),
      );
      expect(signer.lastEnvelope, isNull);
    });

    test('rejects empty calls before signing', () async {
      final signer = _StubSigner(signature: Uint8List(65));
      expect(
        () => signWalletBatch(
          signer: signer,
          walletAddress: _wallet,
          nonce: _nonce,
          deadline: _deadline,
          calls: const [],
        ),
        throwsA(isA<ValidationException>()),
      );
    });

    test('rejects wrong-length signature from wallet', () async {
      final signer = _StubSigner(signature: Uint8List(64));
      expect(
        () => signWalletBatch(
          signer: signer,
          walletAddress: _wallet,
          nonce: _nonce,
          deadline: _deadline,
          calls: _sampleCalls(),
        ),
        throwsA(isA<ValidationException>()),
      );
    });
  });

  group('defaultBatchDeadline', () {
    test('produces an integer-string `secondsFromNow` ahead of `now`', () {
      final base = DateTime.fromMillisecondsSinceEpoch(1700000000000);
      final d = defaultBatchDeadline(secondsFromNow: 240, now: base);
      expect(int.parse(d), 1700000000 + 240);
    });
  });
}

class _StubSigner implements WalletSigner {
  _StubSigner({required this.signature, int chainId = 137})
    : _chainId = chainId;

  final Uint8List signature;
  final int _chainId;
  Map<String, dynamic>? lastEnvelope;

  @override
  String get address => '0x2c7536E3605D9C16a7a3D7b1898e529396a65c23';

  @override
  int get chainId => _chainId;

  @override
  Future<Uint8List> signTypedData(Map<String, dynamic> typedData) async {
    lastEnvelope = typedData;
    return signature;
  }

  @override
  Future<Uint8List> personalSign(Uint8List message) async => signature;
}
