library;

enum CapabilityTier { public, authenticated, wallet, execution, bridge }

enum CapabilityOperation {
  list,
  get,
  search,
  read,
  stream,
  derive,
  sign,
  create,
  submit,
  cancel,
  update,
  simulate,
}

enum CapabilityTransport { local, https, wss, rpc }

enum AuthRequirement { none, l1, l2, siwe }

enum SigningRequirement { none, wallet }

enum CapabilityStatus { implemented, dtoOnly, unsupported, planned }

final class Capability {
  const Capability({
    required this.id,
    required this.tier,
    required this.service,
    required this.operation,
    required this.transport,
    required this.auth,
    required this.signing,
    required this.mutates,
    required this.cliCommand,
    required this.extension,
    required this.summary,
    required this.status,
  });
  final String id;
  final CapabilityTier tier;
  final String service;
  final CapabilityOperation operation;
  final CapabilityTransport transport;
  final List<AuthRequirement> auth;
  final SigningRequirement signing;
  final bool mutates;
  final List<String>? cliCommand;
  final bool extension;
  final String summary;
  final CapabilityStatus status;
  Map<String, dynamic> toJson() => {
    'id': id,
    'tier': tier.name,
    'service': service,
    'operation': operation.name,
    'transport': transport.name,
    'auth': auth.map((value) => value.name).toList(growable: false),
    'signing': signing.name,
    'mutates': mutates,
    'cliCommand': cliCommand,
    'extension': extension,
    'summary': summary,
    'status': status.name,
  };
}

abstract final class CapabilityCatalog {
  static const List<Capability> all = [
    Capability(
      id: "approve.check",
      tier: CapabilityTier.execution,
      service: "approve",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.rpc,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["approve", "check"],
      extension: false,
      summary: "Approve check.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "approve.set",
      tier: CapabilityTier.execution,
      service: "approve",
      operation: CapabilityOperation.submit,
      transport: CapabilityTransport.rpc,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: ["approve", "set"],
      extension: false,
      summary: "Approve set.",
      status: CapabilityStatus.dtoOnly,
    ),
    Capability(
      id: "auth.l1.headers.create",
      tier: CapabilityTier.authenticated,
      service: "auth",
      operation: CapabilityOperation.create,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.l1],
      signing: SigningRequirement.wallet,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Auth l1 headers create.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "auth.l2.headers.create",
      tier: CapabilityTier.authenticated,
      service: "auth",
      operation: CapabilityOperation.create,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Auth l2 headers create.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "auth.siwe.session.create",
      tier: CapabilityTier.authenticated,
      service: "auth",
      operation: CapabilityOperation.create,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.siwe],
      signing: SigningRequirement.wallet,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Auth siwe session create.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "bridge.assets.read",
      tier: CapabilityTier.bridge,
      service: "bridge",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["bridge", "supported-assets"],
      extension: false,
      summary: "Bridge assets read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "bridge.depositAddress.create",
      tier: CapabilityTier.bridge,
      service: "bridge",
      operation: CapabilityOperation.create,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["bridge", "deposit"],
      extension: false,
      summary: "Bridge deposit address create.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "bridge.quote.read",
      tier: CapabilityTier.bridge,
      service: "bridge",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Bridge quote read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "bridge.status.read",
      tier: CapabilityTier.bridge,
      service: "bridge",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["bridge", "status"],
      extension: false,
      summary: "Bridge status read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "bridge.withdraw.simulate",
      tier: CapabilityTier.bridge,
      service: "bridge",
      operation: CapabilityOperation.simulate,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Bridge withdraw simulate.",
      status: CapabilityStatus.planned,
    ),
    Capability(
      id: "bridge.withdraw.submit",
      tier: CapabilityTier.bridge,
      service: "bridge",
      operation: CapabilityOperation.submit,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: null,
      extension: true,
      summary: "Bridge withdraw submit.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "chainlink.price.read",
      tier: CapabilityTier.public,
      service: "chainlink",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.rpc,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Chainlink price read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.accountStatus.read",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "account-status"],
      extension: false,
      summary: "Clob account status read.",
      status: CapabilityStatus.planned,
    ),
    Capability(
      id: "clob.apiKey.createOrDerive",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.create,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l1],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: ["clob", "create-api-key"],
      extension: false,
      summary: "Clob api key create or derive.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.apiKey.delete",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.update,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: true,
      cliCommand: ["clob", "delete-api-key"],
      extension: false,
      summary: "Clob api key delete.",
      status: CapabilityStatus.planned,
    ),
    Capability(
      id: "clob.apiKeys.list",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "api-keys"],
      extension: false,
      summary: "Clob api keys list.",
      status: CapabilityStatus.planned,
    ),
    Capability(
      id: "clob.balance.read",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "balance"],
      extension: false,
      summary: "Clob balance read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.balance.update",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.update,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: true,
      cliCommand: ["clob", "update-balance"],
      extension: false,
      summary: "Clob balance update.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.book.read",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "book"],
      extension: false,
      summary: "Clob book read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.books.batchRead",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "books"],
      extension: false,
      summary: "Clob books batch read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.builderFeeKey.create",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.create,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Clob builder fee key create.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.builderFeeKey.revoke",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.update,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Clob builder fee key revoke.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.builderFeeKeys.list",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Clob builder fee keys list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.builderTrades.list",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Clob builder trades list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.currentRewards.list",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "current-rewards"],
      extension: false,
      summary: "Clob current rewards list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.earnings.read",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "earnings"],
      extension: false,
      summary: "Clob earnings read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.earningsByMarket.list",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "earnings-markets"],
      extension: false,
      summary: "Clob earnings by market list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.feeRate.read",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "fee-rate"],
      extension: false,
      summary: "Clob fee rate read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.geoblock.read",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "geoblock"],
      extension: false,
      summary: "Clob geoblock read.",
      status: CapabilityStatus.planned,
    ),
    Capability(
      id: "clob.health.read",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "ok"],
      extension: false,
      summary: "Clob health read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.lastTrade.read",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "last-trade"],
      extension: false,
      summary: "Clob last trade read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.lastTrades.batchRead",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "last-trades"],
      extension: false,
      summary: "Clob last trades batch read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.market.read",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "market"],
      extension: false,
      summary: "Clob market read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.marketOutcome.resolve",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Clob market outcome resolve.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.marketReward.read",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "market-reward"],
      extension: false,
      summary: "Clob market reward read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.markets.list",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "markets"],
      extension: false,
      summary: "Clob markets list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.midpoint.read",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "midpoint"],
      extension: false,
      summary: "Clob midpoint read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.midpoints.batchRead",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "midpoints"],
      extension: false,
      summary: "Clob midpoints batch read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.negRisk.read",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "neg-risk"],
      extension: false,
      summary: "Clob neg risk read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.notifications.delete",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.update,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: true,
      cliCommand: ["clob", "delete-notifications"],
      extension: false,
      summary: "Clob notifications delete.",
      status: CapabilityStatus.planned,
    ),
    Capability(
      id: "clob.notifications.list",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "notifications"],
      extension: false,
      summary: "Clob notifications list.",
      status: CapabilityStatus.planned,
    ),
    Capability(
      id: "clob.order.cancel",
      tier: CapabilityTier.execution,
      service: "clob",
      operation: CapabilityOperation.cancel,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: ["clob", "cancel"],
      extension: false,
      summary: "Clob order cancel.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.order.read",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "order"],
      extension: false,
      summary: "Clob order read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.orderScoring.read",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "order-scoring"],
      extension: false,
      summary: "Clob order scoring read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.orders.all.cancel",
      tier: CapabilityTier.execution,
      service: "clob",
      operation: CapabilityOperation.cancel,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: ["clob", "cancel-all"],
      extension: false,
      summary: "Clob orders all cancel.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.orders.batch.cancel",
      tier: CapabilityTier.execution,
      service: "clob",
      operation: CapabilityOperation.cancel,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: ["clob", "cancel-orders"],
      extension: false,
      summary: "Clob orders batch cancel.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.orders.batch.submit",
      tier: CapabilityTier.execution,
      service: "clob",
      operation: CapabilityOperation.submit,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: ["clob", "post-orders"],
      extension: false,
      summary: "Clob orders batch submit.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.orders.limit.submit",
      tier: CapabilityTier.execution,
      service: "clob",
      operation: CapabilityOperation.submit,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: ["clob", "create-order"],
      extension: false,
      summary: "Clob orders limit submit.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.orders.list",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "orders"],
      extension: false,
      summary: "Clob orders list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.orders.market.cancel",
      tier: CapabilityTier.execution,
      service: "clob",
      operation: CapabilityOperation.cancel,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: ["clob", "cancel-market"],
      extension: false,
      summary: "Clob orders market cancel.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.orders.market.submit",
      tier: CapabilityTier.execution,
      service: "clob",
      operation: CapabilityOperation.submit,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: ["clob", "market-order"],
      extension: false,
      summary: "Clob orders market submit.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.ordersScoring.read",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "orders-scoring"],
      extension: false,
      summary: "Clob orders scoring read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.price.read",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "price"],
      extension: false,
      summary: "Clob price read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.priceHistory.read",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "price-history"],
      extension: false,
      summary: "Clob price history read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.prices.batchRead",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "batch-prices"],
      extension: false,
      summary: "Clob prices batch read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.publicTrades.list",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Clob public trades list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.rewardPercentages.read",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "reward-percentages"],
      extension: false,
      summary: "Clob reward percentages read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.rewards.list",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "rewards"],
      extension: false,
      summary: "Clob rewards list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.samplingMarkets.list",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "sampling-markets"],
      extension: false,
      summary: "Clob sampling markets list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.simplifiedMarkets.list",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "simplified-markets"],
      extension: false,
      summary: "Clob simplified markets list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.simplifiedSamplingMarkets.list",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "sampling-simp-markets"],
      extension: false,
      summary: "Clob simplified sampling markets list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.spread.read",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "spread"],
      extension: false,
      summary: "Clob spread read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.spreads.batchRead",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "spreads"],
      extension: false,
      summary: "Clob spreads batch read.",
      status: CapabilityStatus.planned,
    ),
    Capability(
      id: "clob.tickSize.read",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "tick-size"],
      extension: false,
      summary: "Clob tick size read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.time.read",
      tier: CapabilityTier.public,
      service: "clob",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "time"],
      extension: false,
      summary: "Clob time read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "clob.trades.list",
      tier: CapabilityTier.authenticated,
      service: "clob",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["clob", "trades"],
      extension: false,
      summary: "Clob trades list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "comments.byUser.list",
      tier: CapabilityTier.public,
      service: "comments",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["comments", "by-user"],
      extension: false,
      summary: "Comments by user list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "comments.get",
      tier: CapabilityTier.public,
      service: "comments",
      operation: CapabilityOperation.get,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["comments", "get"],
      extension: false,
      summary: "Comments get.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "comments.list",
      tier: CapabilityTier.public,
      service: "comments",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["comments", "list"],
      extension: false,
      summary: "Comments list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "ctf.collectionId.derive",
      tier: CapabilityTier.execution,
      service: "ctf",
      operation: CapabilityOperation.derive,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["ctf", "collection-id"],
      extension: false,
      summary: "Ctf collection id derive.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "ctf.conditionId.derive",
      tier: CapabilityTier.execution,
      service: "ctf",
      operation: CapabilityOperation.derive,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["ctf", "condition-id"],
      extension: false,
      summary: "Ctf condition id derive.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "ctf.merge",
      tier: CapabilityTier.execution,
      service: "ctf",
      operation: CapabilityOperation.submit,
      transport: CapabilityTransport.rpc,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: ["ctf", "merge"],
      extension: false,
      summary: "Ctf merge.",
      status: CapabilityStatus.dtoOnly,
    ),
    Capability(
      id: "ctf.positionId.derive",
      tier: CapabilityTier.execution,
      service: "ctf",
      operation: CapabilityOperation.derive,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["ctf", "position-id"],
      extension: false,
      summary: "Ctf position id derive.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "ctf.redeem",
      tier: CapabilityTier.execution,
      service: "ctf",
      operation: CapabilityOperation.submit,
      transport: CapabilityTransport.rpc,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: ["ctf", "redeem"],
      extension: false,
      summary: "Ctf redeem.",
      status: CapabilityStatus.dtoOnly,
    ),
    Capability(
      id: "ctf.redeemNegRisk",
      tier: CapabilityTier.execution,
      service: "ctf",
      operation: CapabilityOperation.submit,
      transport: CapabilityTransport.rpc,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: ["ctf", "redeem-neg-risk"],
      extension: false,
      summary: "Ctf redeem neg risk.",
      status: CapabilityStatus.dtoOnly,
    ),
    Capability(
      id: "ctf.split",
      tier: CapabilityTier.execution,
      service: "ctf",
      operation: CapabilityOperation.submit,
      transport: CapabilityTransport.rpc,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: ["ctf", "split"],
      extension: false,
      summary: "Ctf split.",
      status: CapabilityStatus.dtoOnly,
    ),
    Capability(
      id: "data.activity.read",
      tier: CapabilityTier.public,
      service: "data",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["data", "activity"],
      extension: false,
      summary: "Data activity read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "data.builderLeaderboard.read",
      tier: CapabilityTier.public,
      service: "data",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["data", "builder-leaderboard"],
      extension: false,
      summary: "Data builder leaderboard read.",
      status: CapabilityStatus.planned,
    ),
    Capability(
      id: "data.builderVolume.read",
      tier: CapabilityTier.public,
      service: "data",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["data", "builder-volume"],
      extension: false,
      summary: "Data builder volume read.",
      status: CapabilityStatus.planned,
    ),
    Capability(
      id: "data.closedPositions.read",
      tier: CapabilityTier.public,
      service: "data",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["data", "closed-positions"],
      extension: false,
      summary: "Data closed positions read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "data.holders.read",
      tier: CapabilityTier.public,
      service: "data",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["data", "holders"],
      extension: false,
      summary: "Data holders read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "data.leaderboard.read",
      tier: CapabilityTier.public,
      service: "data",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["data", "leaderboard"],
      extension: false,
      summary: "Data leaderboard read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "data.marketTrades.read",
      tier: CapabilityTier.public,
      service: "data",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Data market trades read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "data.marketsTraded.read",
      tier: CapabilityTier.public,
      service: "data",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["data", "traded"],
      extension: false,
      summary: "Data markets traded read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "data.openInterest.read",
      tier: CapabilityTier.public,
      service: "data",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["data", "open-interest"],
      extension: false,
      summary: "Data open interest read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "data.positions.read",
      tier: CapabilityTier.public,
      service: "data",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["data", "positions"],
      extension: false,
      summary: "Data positions read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "data.smartWalletTrades.read",
      tier: CapabilityTier.public,
      service: "data",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Data smart wallet trades read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "data.trades.read",
      tier: CapabilityTier.public,
      service: "data",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["data", "trades"],
      extension: false,
      summary: "Data trades read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "data.value.read",
      tier: CapabilityTier.public,
      service: "data",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["data", "value"],
      extension: false,
      summary: "Data value read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "data.volume.read",
      tier: CapabilityTier.public,
      service: "data",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["data", "volume"],
      extension: false,
      summary: "Data volume read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "events.get",
      tier: CapabilityTier.public,
      service: "events",
      operation: CapabilityOperation.get,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["events", "get"],
      extension: false,
      summary: "Events get.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "events.list",
      tier: CapabilityTier.public,
      service: "events",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["events", "list"],
      extension: false,
      summary: "Events list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "events.tags.list",
      tier: CapabilityTier.public,
      service: "events",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["events", "tags"],
      extension: false,
      summary: "Events tags list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "intel.marketFlow.read",
      tier: CapabilityTier.public,
      service: "intel",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Intel market flow read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "intel.wallet.alerts",
      tier: CapabilityTier.public,
      service: "intel",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Intel wallet alerts.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "intel.wallet.dossier",
      tier: CapabilityTier.public,
      service: "intel",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Intel wallet dossier.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "intel.wallet.score",
      tier: CapabilityTier.public,
      service: "intel",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Intel wallet score.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "market.discover",
      tier: CapabilityTier.public,
      service: "market",
      operation: CapabilityOperation.search,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Market discover.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "market.resolve",
      tier: CapabilityTier.public,
      service: "market",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Market resolve.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "marketDetail.bundle.read",
      tier: CapabilityTier.public,
      service: "marketDetail",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Market detail bundle read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "markets.get",
      tier: CapabilityTier.public,
      service: "markets",
      operation: CapabilityOperation.get,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["markets", "get"],
      extension: false,
      summary: "Markets get.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "markets.list",
      tier: CapabilityTier.public,
      service: "markets",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["markets", "list"],
      extension: false,
      summary: "Markets list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "markets.search",
      tier: CapabilityTier.public,
      service: "markets",
      operation: CapabilityOperation.search,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["markets", "search"],
      extension: false,
      summary: "Markets search.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "markets.tags.list",
      tier: CapabilityTier.public,
      service: "markets",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["markets", "tags"],
      extension: false,
      summary: "Markets tags list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "opportunities.scan",
      tier: CapabilityTier.public,
      service: "opportunities",
      operation: CapabilityOperation.search,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Opportunities scan.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "orderfills.read",
      tier: CapabilityTier.public,
      service: "orderfills",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.rpc,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Orderfills read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "paper.order.cancel",
      tier: CapabilityTier.public,
      service: "paper",
      operation: CapabilityOperation.cancel,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Paper order cancel.",
      status: CapabilityStatus.planned,
    ),
    Capability(
      id: "paper.order.submit",
      tier: CapabilityTier.public,
      service: "paper",
      operation: CapabilityOperation.submit,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Paper order submit.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "profiles.get",
      tier: CapabilityTier.public,
      service: "profiles",
      operation: CapabilityOperation.get,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["profiles", "get"],
      extension: false,
      summary: "Profiles get.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "relayer.transaction.read",
      tier: CapabilityTier.execution,
      service: "relayer",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.siwe],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Relayer transaction read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "relayer.transaction.submit",
      tier: CapabilityTier.execution,
      service: "relayer",
      operation: CapabilityOperation.submit,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.siwe],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: null,
      extension: true,
      summary: "Relayer transaction submit.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "relayer.wallet.deploy",
      tier: CapabilityTier.execution,
      service: "relayer",
      operation: CapabilityOperation.submit,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.siwe],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: null,
      extension: true,
      summary: "Relayer wallet deploy.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "relayer.wallet.status.read",
      tier: CapabilityTier.execution,
      service: "relayer",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.siwe],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Relayer wallet status read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "rfq.submit",
      tier: CapabilityTier.execution,
      service: "rfq",
      operation: CapabilityOperation.submit,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.wallet,
      mutates: true,
      cliCommand: null,
      extension: true,
      summary: "Rfq submit.",
      status: CapabilityStatus.unsupported,
    ),
    Capability(
      id: "series.get",
      tier: CapabilityTier.public,
      service: "series",
      operation: CapabilityOperation.get,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["series", "get"],
      extension: false,
      summary: "Series get.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "series.list",
      tier: CapabilityTier.public,
      service: "series",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["series", "list"],
      extension: false,
      summary: "Series list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "settlement.readiness.check",
      tier: CapabilityTier.wallet,
      service: "settlement",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.rpc,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Settlement readiness check.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "settlement.redeem.plan",
      tier: CapabilityTier.wallet,
      service: "settlement",
      operation: CapabilityOperation.create,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Settlement redeem plan.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "settlement.redeemables.read",
      tier: CapabilityTier.public,
      service: "settlement",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Settlement redeemables read.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "simulation.book.execute",
      tier: CapabilityTier.public,
      service: "simulation",
      operation: CapabilityOperation.simulate,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Simulation book execute.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "sports.list",
      tier: CapabilityTier.public,
      service: "sports",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["sports", "list"],
      extension: false,
      summary: "Sports list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "sports.marketTypes.list",
      tier: CapabilityTier.public,
      service: "sports",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["sports", "market-types"],
      extension: false,
      summary: "Sports market types list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "sports.teams.list",
      tier: CapabilityTier.public,
      service: "sports",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["sports", "teams"],
      extension: false,
      summary: "Sports teams list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "stream.market.subscribe",
      tier: CapabilityTier.public,
      service: "stream",
      operation: CapabilityOperation.stream,
      transport: CapabilityTransport.wss,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Stream market subscribe.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "stream.user.subscribe",
      tier: CapabilityTier.authenticated,
      service: "stream",
      operation: CapabilityOperation.stream,
      transport: CapabilityTransport.wss,
      auth: [AuthRequirement.l2],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Stream user subscribe.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "tags.get",
      tier: CapabilityTier.public,
      service: "tags",
      operation: CapabilityOperation.get,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["tags", "get"],
      extension: false,
      summary: "Tags get.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "tags.list",
      tier: CapabilityTier.public,
      service: "tags",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["tags", "list"],
      extension: false,
      summary: "Tags list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "tags.related.list",
      tier: CapabilityTier.public,
      service: "tags",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["tags", "related"],
      extension: false,
      summary: "Tags related list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "tags.relatedTags.list",
      tier: CapabilityTier.public,
      service: "tags",
      operation: CapabilityOperation.list,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["tags", "related-tags"],
      extension: false,
      summary: "Tags related tags list.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "wallet.address.read",
      tier: CapabilityTier.wallet,
      service: "wallet",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: ["wallet", "address"],
      extension: false,
      summary: "Wallet address read.",
      status: CapabilityStatus.planned,
    ),
    Capability(
      id: "wallet.batch.sign",
      tier: CapabilityTier.wallet,
      service: "wallet",
      operation: CapabilityOperation.sign,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.wallet,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Wallet batch sign.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "wallet.deposit.derive",
      tier: CapabilityTier.wallet,
      service: "wallet",
      operation: CapabilityOperation.derive,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Wallet deposit derive.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "wallet.proxy.derive",
      tier: CapabilityTier.wallet,
      service: "wallet",
      operation: CapabilityOperation.derive,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Wallet proxy derive.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "wallet.readiness.check",
      tier: CapabilityTier.wallet,
      service: "wallet",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.rpc,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Wallet readiness check.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "wallet.safe.derive",
      tier: CapabilityTier.wallet,
      service: "wallet",
      operation: CapabilityOperation.derive,
      transport: CapabilityTransport.local,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Wallet safe derive.",
      status: CapabilityStatus.implemented,
    ),
    Capability(
      id: "web.cryptoMarkets.read",
      tier: CapabilityTier.public,
      service: "web",
      operation: CapabilityOperation.read,
      transport: CapabilityTransport.https,
      auth: [AuthRequirement.none],
      signing: SigningRequirement.none,
      mutates: false,
      cliCommand: null,
      extension: true,
      summary: "Web crypto markets read.",
      status: CapabilityStatus.implemented,
    ),
  ];
  static Capability? byId(String id) {
    var low = 0;
    var high = all.length - 1;
    while (low <= high) {
      final middle = (low + high) >> 1;
      final comparison = all[middle].id.compareTo(id);
      if (comparison == 0) return all[middle];
      if (comparison < 0) {
        low = middle + 1;
      } else {
        high = middle - 1;
      }
    }
    return null;
  }
}
