// Parity vectors generated by polygolem `cmd/parity_erc7739`.
// Inputs: canonical OrderV2Draft (salt=1, maker=signer=depositWallet,
// tokenId=12345, makerAmount=5500000, takerAmount=10000000, side=BUY,
// signatureType=poly1271, timestamp=1700000000000), depositWallet=
// 0xfd5041047be8c192c725a66228f141196fa3cf9c, negRisk=false/true,
// chainId=137.
import 'dart:typed_data';

import 'package:polydart/src/auth/erc7739.dart';
import 'package:polydart/src/auth/eth_hex.dart';
import 'package:polydart/src/errors/errors.dart';
import 'package:polydart/src/orders/order_signing.dart';
import 'package:test/test.dart';

import '../../support/auth_test_fixtures.dart';
import '../../support/fake_wallet_signer.dart';
import '../shared/poly1271_test_values.dart';

void main() {
  group('ERC-7739 parity (cross-validated against polygolem)', () {
    test('TypedDataSign typehash', () {
      expect(
        bytesToHex(poly1271TypedDataSignTypeHash()),
        '6ba028565cb324c2aa02bb714b9816d0bddd557a2f33bb36cf13272a4256bd42',
      );
    });

    test('contents (Order struct hash) for sigtype=3 variant', () {
      final contents = orderV2StructHash(draft: canonicalPoly1271OrderDraft());
      expect(
        bytesToHex(contents),
        '662e2e1befa43fad015c08b6b0832c68fa42980e84e5f4a8b71c8ff532e14e03',
      );
    });

    test('hashStruct(TypedDataSign) for canonical sample', () {
      final tds = poly1271StructHash(
        contents: orderV2StructHash(draft: canonicalPoly1271OrderDraft()),
        depositWalletAddress: canonicalDepositWallet,
      );
      expect(
        bytesToHex(tds),
        '5c2dcd83af101e0ddcfdf863c9e2462a3a715a33c7033ca82d51cacb40d4a47e',
      );
    });

    test('final hash for canonical regular-market sample', () {
      final digest = computePoly1271FinalHash(
        draft: canonicalPoly1271OrderDraft(),
        depositWalletAddress: canonicalDepositWallet,
      );
      expect(
        bytesToHex(digest),
        '495e95c0ae70519abcebd1cb85594e404bea1255b2efb80067c2200e9f74c054',
      );
    });

    test('final hash for canonical neg-risk-market sample', () {
      final digest = computePoly1271FinalHash(
        draft: canonicalPoly1271OrderDraft(),
        depositWalletAddress: canonicalDepositWallet,
        negRisk: true,
      );
      expect(
        bytesToHex(digest),
        '591a51c2e3500129b6955abe546a788b2815a909dff55acf7c132b13058127b1',
      );
    });

    test('contentsType is 186 bytes', () {
      // Already verified in order_signing_test, but reasserted here so a
      // schema change is caught by the wrap layout test too.
      expect(orderV2ContentsType.length, 186);
    });

    test('digest derived from typed-data envelope matches direct compute', () {
      // poly1271DigestFromEnvelope re-walks the EIP-712 pipeline a wallet
      // would run on the envelope returned by
      // buildPoly1271TypedDataEnvelope. It must produce the same digest
      // as computePoly1271FinalHash.
      final draft = canonicalPoly1271OrderDraft();
      final a = computePoly1271FinalHash(
        draft: draft,
        depositWalletAddress: canonicalDepositWallet,
      );
      final b = poly1271DigestFromEnvelope(
        draft: draft,
        depositWalletAddress: canonicalDepositWallet,
      );
      expect(bytesToHex(a), bytesToHex(b));
    });
  });

  group('assembled wrap layout', () {
    test('317 bytes total with deterministic placeholder sig', () {
      final placeholder = deterministicInnerSignature65();
      final assembled = assemblePoly1271WrappedSignature(
        innerSignature: placeholder,
        draft: canonicalPoly1271OrderDraft(),
      );
      // 0x prefix + 634 hex chars = 636 chars total = 317 bytes.
      expect(assembled.length, 636);
      expect(assembled.startsWith('0x'), isTrue);

      // Cross-validate against polygolem-emitted full-wrap fixture.
      const expected =
          '0x'
          'a0a1a2a3a4a5a6a7a8a9aaabacadaeaf'
          'a0a1a2a3a4a5a6a7a8a9aaabacadaeaf'
          'a0a1a2a3a4a5a6a7a8a9aaabacadaeaf'
          'a0a1a2a3a4a5a6a7a8a9aaabacadaeaf'
          'a0'
          // appDomainSep
          '3264e159346253e26a64e00b69032db0e7d32f94628de3e6eecb50304d7af3d2'
          // contents (Order struct hash for sigtype=3 variant)
          '662e2e1befa43fad015c08b6b0832c68fa42980e84e5f4a8b71c8ff532e14e03'
          // contentsType (186 bytes ASCII)
          '4f726465722875696e743235362073616c742c61646472657373206d616b65722c61646472657373207369676e65722c75696e7432353620746f6b656e49642c75696e74323536206d616b6572416d6f756e742c75696e743235362074616b6572416d6f756e742c75696e743820736964652c75696e7438207369676e6174757265547970652c75696e743235362074696d657374616d702c62797465733332206d657461646174612c62797465733332206275696c64657229'
          // uint16BE(186) = 0x00ba
          '00ba';
      expect(assembled, expected);
    });

    test('neg-risk wrap swaps only the app domain separator', () {
      final placeholder = deterministicInnerSignature65();
      final assembled = assemblePoly1271WrappedSignature(
        innerSignature: placeholder,
        draft: canonicalPoly1271OrderDraft(),
        negRisk: true,
      );
      const expected =
          '0x'
          'a0a1a2a3a4a5a6a7a8a9aaabacadaeaf'
          'a0a1a2a3a4a5a6a7a8a9aaabacadaeaf'
          'a0a1a2a3a4a5a6a7a8a9aaabacadaeaf'
          'a0a1a2a3a4a5a6a7a8a9aaabacadaeaf'
          'a0'
          // neg-risk appDomainSep
          '9b858f53327b0bd13af8ec14cfb35234fb9eb7b0504d1a4e61f433840d30e81a'
          // contents (unchanged Order struct hash)
          '662e2e1befa43fad015c08b6b0832c68fa42980e84e5f4a8b71c8ff532e14e03'
          // contentsType (186 bytes ASCII)
          '4f726465722875696e743235362073616c742c61646472657373206d616b65722c61646472657373207369676e65722c75696e7432353620746f6b656e49642c75696e74323536206d616b6572416d6f756e742c75696e743235362074616b6572416d6f756e742c75696e743820736964652c75696e7438207369676e6174757265547970652c75696e743235362074696d657374616d702c62797465733332206d657461646174612c62797465733332206275696c64657229'
          '00ba';
      expect(assembled, expected);
    });

    test('rejects non-65-byte innerSignature', () {
      expect(
        () => assemblePoly1271WrappedSignature(
          innerSignature: Uint8List(64),
          draft: canonicalPoly1271OrderDraft(),
        ),
        throwsA(isA<Exception>()),
      );
    });
  });

  group('typed-data envelope shape', () {
    test('matches the wallet provider format', () {
      final env = buildPoly1271TypedDataEnvelope(
        draft: canonicalPoly1271OrderDraft(),
        depositWalletAddress: canonicalDepositWallet,
      );
      expect(env['primaryType'], 'TypedDataSign');
      final domain = env['domain'] as Map<String, dynamic>;
      expect(domain['name'], 'Polymarket CTF Exchange');
      expect(domain['version'], '2');
      // Inline DepositWallet domain values appear in the message, not the
      // outer domain — the OUTER domain is the CTF Exchange app domain.
      final msg = env['message'] as Map<String, dynamic>;
      expect(msg['name'], 'DepositWallet');
      expect(msg['version'], '1');
      expect(msg['verifyingContract'], canonicalDepositWallet);
      expect(msg['salt'], bytes32Zero);
      // contents must be the full Order struct.
      final contents = msg['contents'] as Map<String, dynamic>;
      expect(contents['tokenId'], '12345');
      expect(contents['signatureType'], 3);
      expect(contents['side'], 0);
    });
  });

  group('wrapPoly1271Signature (WalletSigner integration)', () {
    test('passes the envelope to the signer and assembles the wrap', () async {
      final signer = FakeWalletSigner(
        signature: deterministicInnerSignature65(),
      );
      final wrapped = await wrapPoly1271Signature(
        signer: signer,
        draft: canonicalPoly1271OrderDraft(),
        depositWalletAddress: canonicalDepositWallet,
      );
      // Sanity: 636 chars and the captured envelope used chainId=137.
      expect(wrapped.length, 636);
      expect(signer.lastTypedData, isNotNull);
      final domain = signer.lastTypedData!['domain'] as Map<String, dynamic>;
      expect(domain['chainId'], 137);
    });

    test('rejects non-Polygon signer before wallet signing', () async {
      final signer = FakeWalletSigner(signature: Uint8List(65), chainId: 80002);

      await expectLater(
        () => wrapPoly1271Signature(
          signer: signer,
          draft: canonicalPoly1271OrderDraft(),
          depositWalletAddress: canonicalDepositWallet,
        ),
        throwsA(
          isA<ValidationException>()
              .having(
                (error) => error.message,
                'message',
                contains('POLY_1271 signing requires Polygon chainId=137'),
              )
              .having((error) => error.field, 'field', 'chainId'),
        ),
      );
      expect(signer.signTypedDataCalls, 0);
      expect(signer.lastTypedData, isNull);
    });

    test('rejects wallet signatures of wrong length', () async {
      final signer = FakeWalletSigner(signature: Uint8List(64));
      expect(
        () => wrapPoly1271Signature(
          signer: signer,
          draft: canonicalPoly1271OrderDraft(),
          depositWalletAddress: canonicalDepositWallet,
        ),
        throwsA(isA<Exception>()),
      );
    });
  });
}
